# demangler=undname.exe
objdumper=/opt/mingw/bin/objdump.exe

################################
# Windows Compilers
group.cl.compilers=&cl19
group.cl.needsMulti=false
group.cl.compilerType=WSL-CL
group.cl.includeFlag=/I
group.cl.versionFlag=/?
group.cl.versionRe=^Microsoft \(R\) C/C\+\+.*$
group.cl.demangler=undname.exe

group.cl19.compilers=cl19_64
group.cl19.options=
compiler.cl19_64.exe=cl.exe
compiler.cl19_64.name=x86-64 CL 19 2017 RTW

group.gcc86.compilers=grecent
group.gcc86.groupName=GCC x86-64
group.gcc86.compilerType=gcc
compiler.grecent.exe=g++.exe
compiler.grecent.name=x86-64 gcc
