# Default settings for Pascal
compilers=&fpc
defaultCompiler=fpc304
postProcess=
demangler=/dev/null
options=
versionFlag=-h
supportsBinary=true
compilerType=pascal
objdumper=/fpc/3.0.4/bin/i386-win32/x86_64-win64-objdump.exe

group.fpc.compilers=fpc304:fpc304_64

compiler.fpc304.exe=/fpc/3.0.4/bin/i386-win32/fpc.exe
compiler.fpc304.name=x86 fpc 3.0.4

compiler.fpc304_64.exe=/fpc/3.0.4/bin/i386-win32/ppcrossx64.exe
compiler.fpc304_64.name=x86-64 fpc 3.0.4

#################################
#################################
# Installed libs (See c++.amazon.properties for a scheme of libs group)
libs=
